//! Build-time generation of schema-language's parenthesis-reference dispatch.
//!
//! schema-language-cc owns the dispatch as data: it decodes + validates the canonical
//! `ReferenceGrammar` (`schemas/reference-grammar.nota`) and emits the real
//! resolver method body. This script writes that emission to a COMMITTED,
//! freshness-gated source file (`src/reference_resolver_generated.rs`) which
//! the library `include!`s.
//!
//! The committed file is the artifact reviewers read; the build verifies it is
//! fresh on every compile. The freshness gate mirrors schema-rust's
//! `GeneratedArtifact`: with `SCHEMA_UPDATE_RESOLVER` set the script
//! (re)writes the file from the grammar; unset, it byte-compares the on-disk
//! file against the freshly-emitted source and FAILS the build on any drift —
//! so the generated dispatch can never silently diverge from the grammar.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use nota::StructuralMacroNode;
use schema_language_cc::{ReferenceDispatch, ReferenceGrammar, ValidatedReferenceGrammar};

const GRAMMAR_PATH: &str = "schemas/reference-grammar.nota";
const GENERATED_PATH: &str = "src/reference_resolver_generated.rs";
const UPDATE_VARIABLE: &str = "SCHEMA_UPDATE_RESOLVER";
const GENERATED_HEADER: &str = "\
// GENERATED by schema-language-cc from schemas/reference-grammar.nota — do not edit by
// hand. Edit the grammar, then regenerate with
// `SCHEMA_UPDATE_RESOLVER=1 cargo build`. The build fails on drift.
";

fn main() -> ExitCode {
    println!("cargo:rerun-if-changed={GRAMMAR_PATH}");
    println!("cargo:rerun-if-changed={GENERATED_PATH}");
    println!("cargo:rerun-if-env-changed={UPDATE_VARIABLE}");

    let resolver = match GeneratedResolver::from_grammar_file(Path::new(GRAMMAR_PATH)) {
        Ok(resolver) => resolver,
        Err(report) => {
            eprintln!("schema-language build: {report}");
            return ExitCode::FAILURE;
        }
    };
    match resolver.write_or_check(
        Path::new(GENERATED_PATH),
        env::var_os(UPDATE_VARIABLE).is_some(),
    ) {
        Ok(()) => ExitCode::SUCCESS,
        Err(report) => {
            eprintln!("schema-language build: {report}");
            ExitCode::FAILURE
        }
    }
}

/// The generated parenthesis-reference resolver as committable Rust source:
/// the header plus schema-language-cc's emitted dispatch over schema-language's real types.
/// Owns its content so the freshness gate (write-or-byte-compare) is a method
/// on the artifact, not a free helper.
struct GeneratedResolver {
    source: String,
}

impl GeneratedResolver {
    /// Decode + validate the canonical grammar at `grammar_path` and emit the
    /// resolver source from it via schema-language-cc.
    fn from_grammar_file(grammar_path: &Path) -> Result<Self, String> {
        let nota = fs::read_to_string(grammar_path)
            .map_err(|error| format!("reading {}: {error}", grammar_path.display()))?;
        let grammar = ReferenceGrammar::from_structural_nota(&nota)
            .map_err(|error| format!("decoding {}: {error}", grammar_path.display()))?;
        let validated = ValidatedReferenceGrammar::try_from(grammar)
            .map_err(|error| format!("validating {}: {error}", grammar_path.display()))?;
        let dispatch = ReferenceDispatch::from(&validated).to_dispatch_source();
        Ok(Self {
            source: format!("{GENERATED_HEADER}\n{dispatch}"),
        })
    }

    /// Write the source to `path` when `update` is set; otherwise byte-compare
    /// the on-disk file and report drift (or a missing file) as an error.
    fn write_or_check(&self, path: &Path, update: bool) -> Result<(), String> {
        let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap_or_default());
        let target = manifest.join(path);
        if update {
            return fs::write(&target, &self.source)
                .map_err(|error| format!("writing {}: {error}", target.display()));
        }
        match fs::read_to_string(&target) {
            Ok(existing) if existing == self.source => Ok(()),
            Ok(_) => Err(format!(
                "generated resolver {} is stale; regenerate with {UPDATE_VARIABLE}=1 cargo build",
                target.display()
            )),
            Err(error) => Err(format!(
                "reading generated resolver {} ({error}); regenerate with {UPDATE_VARIABLE}=1 cargo build",
                target.display()
            )),
        }
    }
}
