//! Emission of schema-language's REAL parenthesis-reference dispatch.
//!
//! This module emits the dispatch schema-language actually links: a method body
//! over schema-language's real types (`Self` = `TypeReference`, `SchemaError`,
//! `MacroRegistry`, `MacroContext`, `Block`). schema-language-cc is co-located with
//! schema-language as a workspace member, so naming those types in the emitted
//! text is sound — the generated source compiles into schema, not
//! schema-language-cc. (This emission replaced the v0 standalone resolver, which only
//! proved structure and precedence over abstract placeholders with `todo!()`
//! arms; that second mechanism could silently drift from the real one, so it
//! was retired in favor of this single, consumed emission.)
//!
//! The emitted body is precedence-ordered exactly as the grammar declares:
//! each `Builtin` head/arity arm dispatches to schema-language's uniform
//! `resolve_<snake>` construction method; then the reserved-head guard
//! (derived from the grammar's built-in set, not a hand-written enum) maps an
//! arity-mismatched reserved head to `UnknownTypeReferenceForm`; then the
//! fallback tail `Self::from_macro_or_application` carries the
//! `DeclaredMacro` (registry) and `Application` (generic) rungs that stay in
//! schema.
//!
//! Nothing here interprets the grammar at runtime: the output is Rust text,
//! committed and freshness-gated by schema-language's `build.rs`.

use crate::grammar::{BuiltinArity, BuiltinHead, ReferenceForm};
use crate::validate::ValidatedReferenceGrammar;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// schema-language's parenthesis-reference dispatch, emitted from a validated
/// grammar as a Rust token stream and pretty-printed source.
///
/// Built via `From<&ValidatedReferenceGrammar>`; rendered to committable
/// source with [`ReferenceDispatch::to_dispatch_source`].
#[derive(Clone)]
pub struct ReferenceDispatch {
    tokens: TokenStream,
}

impl ReferenceDispatch {
    /// The emitted dispatch as a token stream.
    pub fn tokens(&self) -> &TokenStream {
        &self.tokens
    }

    /// The emitted dispatch pretty-printed as Rust source in one
    /// `prettyplease` pass. Panics only if the emitted tokens are not
    /// parseable Rust — a generator bug, not a runtime condition.
    pub fn to_dispatch_source(&self) -> String {
        let file = syn::parse2::<syn::File>(self.tokens.clone())
            .expect("emitted dispatch tokens parse as a Rust file");
        prettyplease::unparse(&file)
    }
}

impl From<&ValidatedReferenceGrammar> for ReferenceDispatch {
    fn from(grammar: &ValidatedReferenceGrammar) -> Self {
        let builtin_arms = grammar
            .forms()
            .iter()
            .filter_map(BuiltinDispatchArm::from_form)
            .map(|arm| arm.tokens());

        let reserved_guard = ReservedHeadGuard::from_grammar(grammar).tokens();

        // The fallback tail. Validation guarantees the shape
        // `Builtin* DeclaredMacro? Application`, so the DeclaredMacro
        // (registry) and Application (generic) rungs both land in
        // schema-language's `from_macro_or_application`, which implements
        // registry-then-application. Both markers map to that one tail; no
        // emitted stage exists that the grammar did not declare.
        let fallback_tail = quote! {
            Self::from_macro_or_application(block, registry, context)
        };

        Self {
            tokens: quote! {
                impl TypeReference {
                    /// Lower a parenthesised reference. GENERATED by schema-language-cc
                    /// from the canonical `ReferenceGrammar` — do not edit by
                    /// hand; edit the grammar and regenerate (see this crate's
                    /// `build.rs`).
                    ///
                    /// Dispatch order is the grammar's declared precedence,
                    /// which is deliberately not compiler-checked (the
                    /// application form structurally overlaps every built-in
                    /// and declared head): each canonical built-in head
                    /// (`(Vector T)`, `(Optional T)`, `(ScopeOf T)`,
                    /// `(Map K V)`, `(Bytes N)`) is the direct fast path; a
                    /// reserved head at the wrong arity is an error, never a
                    /// fall-through; then the registry-then-application tail.
                    pub(crate) fn resolve_parenthesis_reference(
                        block: &Block,
                        objects: &[Block],
                        registry: &MacroRegistry,
                        context: &mut MacroContext,
                    ) -> Result<Self, SchemaError> {
                        let head = objects.first().and_then(Block::demote_to_string);
                        let object_count = objects.len();
                        #(#builtin_arms)*
                        #reserved_guard
                        #fallback_tail
                    }
                }
            },
        }
    }
}

/// One emitted built-in dispatch arm: a reserved head plus the parenthesis
/// object count it must hold, mapped to schema-language's uniform construction
/// method `resolve_<snake>`. Carries the data each arm reads, so the emission
/// is a method on that data rather than a free helper.
struct BuiltinDispatchArm<'form> {
    head: &'form BuiltinHead,
    arity: &'form BuiltinArity,
}

impl<'form> BuiltinDispatchArm<'form> {
    fn from_form(form: &'form ReferenceForm) -> Option<Self> {
        match form {
            ReferenceForm::Builtin(head, arity) => Some(Self { head, arity }),
            ReferenceForm::DeclaredMacro | ReferenceForm::Application => None,
        }
    }

    /// The `resolve_<snake>` method name schema exposes for this head:
    /// `resolve_` followed by the head's PascalCase spelling in snake_case
    /// (`ScopeOf` -> `resolve_scope_of`).
    fn resolver_method(&self) -> proc_macro2::Ident {
        format_ident!("resolve_{}", self.head.to_snake_case())
    }

    /// An early-return arm: this head at exactly this object count dispatches
    /// to its construction method, before any later form is consulted.
    fn tokens(&self) -> TokenStream {
        let head = self.head.as_str();
        let object_count = self.arity.block_object_count();
        let method = self.resolver_method();
        quote! {
            if head == Some(#head) && object_count == #object_count {
                return Self::#method(block, objects, registry, context);
            }
        }
    }
}

/// The reserved-head guard, derived from the whole built-in set: a head that
/// is reserved but arrived with no matching arity arm is an
/// `UnknownTypeReferenceForm` error, never a fall-through to the application
/// catch-all. The reserved set is the grammar's declared built-in heads — the
/// guard is sourced from grammar data, not a hand-written head enum.
struct ReservedHeadGuard<'grammar> {
    grammar: &'grammar ValidatedReferenceGrammar,
}

impl<'grammar> ReservedHeadGuard<'grammar> {
    fn from_grammar(grammar: &'grammar ValidatedReferenceGrammar) -> Self {
        Self { grammar }
    }

    fn tokens(&self) -> TokenStream {
        let reserved: Vec<&str> = self
            .grammar
            .forms()
            .iter()
            .filter_map(ReferenceForm::builtin_head)
            .map(BuiltinHead::as_str)
            .collect();
        if reserved.is_empty() {
            return TokenStream::new();
        }
        let reserved_constant = format_ident!("RESERVED_BUILTIN_HEADS");
        quote! {
            const #reserved_constant: &[&str] = &[#(#reserved),*];
            if let Some(head) = head
                && #reserved_constant.contains(&head)
            {
                return Err(SchemaError::UnknownTypeReferenceForm {
                    head: head.to_owned(),
                    argument_count: object_count.saturating_sub(1),
                });
            }
        }
    }
}
