// GENERATED by schema-language-cc from schemas/reference-grammar.nota — do not edit by
// hand. Edit the grammar, then regenerate with
// `SCHEMA_UPDATE_RESOLVER=1 cargo build`. The build fails on drift.

impl TypeReference {
    /// Lower a parenthesised reference. GENERATED by schema-language-cc
    /// from the canonical `ReferenceGrammar` — do not edit by
    /// hand; edit the grammar and regenerate (see this crate's
    /// `build.rs`).
    ///
    /// Dispatch order is the grammar's declared precedence,
    /// which is deliberately not compiler-checked (the
    /// application form structurally overlaps every built-in
    /// and declared head): each canonical built-in head
    /// (`(Vector T)`, `(Optional T)`, `(ScopeOf T)`,
    /// `(Map K V)`, `(Bytes N)`) is the direct fast path; a
    /// reserved head at the wrong arity is an error, never a
    /// fall-through; then the registry-then-application tail.
    pub(crate) fn resolve_parenthesis_reference(
        block: &Block,
        objects: &[Block],
        registry: &MacroRegistry,
        context: &mut MacroContext,
    ) -> Result<Self, SchemaError> {
        let head = objects.first().and_then(Block::demote_to_string);
        let object_count = objects.len();
        if head == Some("Vector") && object_count == 2usize {
            return Self::resolve_vector(block, objects, registry, context);
        }
        if head == Some("Optional") && object_count == 2usize {
            return Self::resolve_optional(block, objects, registry, context);
        }
        if head == Some("ScopeOf") && object_count == 2usize {
            return Self::resolve_scope_of(block, objects, registry, context);
        }
        if head == Some("Map") && object_count == 3usize {
            return Self::resolve_map(block, objects, registry, context);
        }
        if head == Some("Bytes") && object_count == 2usize {
            return Self::resolve_bytes(block, objects, registry, context);
        }
        const RESERVED_BUILTIN_HEADS: &[&str] = &[
            "Vector",
            "Optional",
            "ScopeOf",
            "Map",
            "Bytes",
        ];
        if let Some(head) = head && RESERVED_BUILTIN_HEADS.contains(&head) {
            return Err(SchemaError::UnknownTypeReferenceForm {
                head: head.to_owned(),
                argument_count: object_count.saturating_sub(1),
            });
        }
        Self::from_macro_or_application(block, registry, context)
    }
}
